apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pos-system
resources:
  - namespace.yaml
  - postgres.yaml
  - payment-processor-mock.yaml
  - app-config.yaml
  - app-secret.yaml
  - pos-api.yaml
  - istio-ingress.yaml
configMapGenerator:
  - name: wiremock-mappings
    files:
      - authorize.json=wiremock/authorize.json
      - confirm.json=wiremock/confirm.json
      - void.json=wiremock/void.json
