apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-pos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: __REPO_URL__
    targetRevision: __TARGET_REVISION__
    path: infra/k8s/overlays/local-kind
  destination:
    server: https://kubernetes.default.svc
    namespace: pos-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
